
export const translations: any = {
  en: {
    common: { 
      cancel: 'Cancel', active: 'Active', expired: 'Expired', banned: 'Banned', 
      saveChanges: 'Save Changes', username: 'Username', status: 'Status', 
      actions: 'Actions', create: 'Create', delete: 'Delete', price: 'Price', 
      currency: 'Currency', duration: 'Duration', traffic: 'Traffic', buy: 'Purchase', 
      email: 'Email', pay: 'Pay Now', gateway: 'Gateway', subLink: 'Subscription Link', 
      copy: 'Copy', copied: 'Copied!', telegram: 'Telegram ID', trackId: 'Tracking ID',
      back: 'Back', close: 'Close', next: 'Next', download: 'Download', recommendedApps: 'Recommended Apps'
    },
    nav: { 
      signOut: 'Sign Out', dashboard: 'Dashboard', users: 'Users', 
      settings: 'Settings', system: 'System Status', store: 'Store Admin', 
      disk: 'Disk Usage' 
    },
    wizard: {
      title: 'Installation Wizard',
      branding: {
          title: 'Brand Identity',
          description: 'Configure the look and feel of your panel.',
          siteTitle: 'Site Title',
          logoUrl: 'Logo URL (Optional)'
      },
      role: { title: 'Server Role', description: 'Select the role of this server.', germany: 'Upstream (Foreign)', germanyDesc: 'Located outside Iran. Generates connection keys.', iran: 'Edge (Iran)', iranDesc: 'Located inside Iran. Connects to Upstream.', next: 'Next Step' },
      external: {
         genKeyTitle: 'Generate Connection Key',
         genKeyDesc: 'Copy this token. You will need to paste it into your Iran Server setup wizard to link them.',
         tokenLabel: 'Connection Token',
         genKeyNote: 'This token contains your server IP and Auth Key.'
      },
      iran: {
         enterKeyTitle: 'Connect to Upstream',
         enterKeyDesc: 'Paste the Connection Token generated by your External (Foreign) server here.',
         keyLabel: 'Connection Token',
         placeholder: 'EL-LINK-...',
         verifyBtn: 'Verify Connection',
         verified: 'Upstream Verified'
      },
      finish: { doneButton: 'Finish Installation' }
    },
    store: {
      title: 'Service Plans',
      heroTitle: 'Secure Access to International Services',
      heroDesc: 'Legal and stable solution for Developers, Traders, and Freelancers to bypass unfair sanctions.',
      bestValue: 'Best Value',
      checkoutTitle: 'Checkout',
      contactInfo: 'Contact Information',
      paymentMethod: 'Select Payment Gateway',
      processing: 'Connecting to Gateway...',
      successTitle: 'Payment Successful',
      successDesc: 'Service activated successfully. Your connection details are below.',
      failTitle: 'Payment Failed',
      failDesc: 'Transaction was rejected. Please try again.',
      retry: 'Try Again',
      sanctionedApps: 'Optimized For',
      compliance: 'Operating under the regulations of the Islamic Republic of Iran.',
      noIllegal: 'Access to immoral content, gambling, and anti-state media is strictly blocked.',
      buy: 'Purchase Plan'
    },
    // ... Settings translations ...
    settings: {
        title: 'System Settings',
        tabs: { general: 'General', store: 'Store & Plans', branding: 'Branding', network: 'Network', security: 'Security', installer: 'Installer', integrations: 'Integrations' },
        credentials: { title: 'Admin Credentials', newUser: 'New Username', newPass: 'New Password', success: 'Credentials updated successfully.' },
        branding: { title: 'Branding', name: 'Brand Name', logo: 'Logo URL / Upload', preview: 'Preview', saveSuccess: 'Branding updated.' },
        storeMgmt: { title: 'Store Configuration', currency: 'Currency Unit', gateways: 'Payment Gateways', merchant: 'Merchant ID / Token', packages: 'Service Packages', edit: 'Edit', save: 'Save' },
        telegram: {
            title: 'Telegram Bot',
            description: 'Manage users and send notifications via Telegram.',
            token: 'Bot Token',
            adminId: 'Admin Chat ID',
            enableBot: 'Enable Bot',
            enableProxy: 'Route API through Foreign Server',
            test: 'Test Connection',
            testing: 'Testing...',
            testSuccess: 'Connection successful!',
            testFail: 'Connection failed. Check logs.',
            instructionsTitle: 'How to get your credentials:',
            instructions1: '1. Talk to <a href="https://t.me/BotFather" target="_blank" class="text-blue-400 underline">@BotFather</a> on Telegram and create a new bot to get your <strong class="text-white">Token</strong>.',
            instructions2: '2. Talk to <a href="https://t.me/userinfobot" target="_blank" class="text-blue-400 underline">@userinfobot</a> to get your numerical <strong class="text-white">Chat ID</strong>.',
            proxyNoteTitle: 'Important Note',
            proxyNote: 'Because Telegram is blocked in your region, you MUST keep the proxy option enabled to communicate with the API via your foreign server.'
        },
        domain: { 
            title: 'Domain & SSL', 
            description: 'Configure your custom domain for subscription links.', 
            saveSuccess: 'Domain saved.',
            domainName: 'Domain Name',
            domainPlaceholder: 'example.com',
            subscriptionDomain: 'Subscription Subdomain',
            subscriptionDomainDesc: 'Optional. e.g., "sub".',
            subscriptionDomainPlaceholder: 'sub',
            invalidDomainError: 'Invalid domain format',
            instructionsTitle: 'Instructions',
            instructions: '1. Point your domain A record to this server IP.\n2. Click "Get Certificate" to generate SSL.',
            healthCheckTitle: 'Domain Health',
            pruneBtn: 'Prune List',
            checkHealthBtn: 'Check Health',
            checkingHealthBtn: 'Checking...',
            status: { untested: 'Untested', testing: 'Testing', healthy: 'Healthy', filtered: 'Filtered' },
            certPath: 'Certificate Path',
            keyPath: 'Private Key Path',
            getCertButton: 'Get Free SSL Certificate',
            gettingCertButton: 'Requesting Let\'s Encrypt...',
            getCertSuccess: 'SSL Certificate installed successfully.',
            getCertError: 'Failed to get certificate. Check DNS.'
        },
        endpoint: {
            title: 'Tunnel Strategy',
            description: 'Select the optimal routing strategy based on network conditions.',
            blockchain: 'Blockchain Relay',
            blockchainDesc: 'Decentralized routing.',
            applyButton: 'Apply Strategy',
            success: 'Strategy applied successfully.'
        },
        camouflage: {
            title: 'Traffic Camouflage',
            description: 'Mimic legitimate traffic patterns to evade detection.',
            profile: 'Traffic Profile',
            profileDesc: { ai: 'AI Model Training', data: 'Database Sync', media: 'Video Streaming' },
            frequency: 'Rotation Frequency',
            lessFrequent: 'Stable',
            moreFrequent: 'Dynamic',
            status: 'Engine Status'
        },
        appCamouflage: {
            title: 'Application Layer Camouflage',
            description: 'Masquerade traffic as popular game protocols.',
            enable: 'Enable Game Protocol Emulation',
            profile: 'Game Profile',
            codm: 'Call of Duty Mobile',
            codmDesc: 'UDP/443 Emulation',
            pubg: 'PUBG Mobile',
            pubgDesc: 'UDP/10000+ Emulation',
            clash: 'Clash Royale',
            clashDesc: 'TCP/9339 Emulation',
            mmorpg: 'Generic MMORPG',
            mmorpgDesc: 'Mixed TCP/UDP',
            liveStatus: 'Live Status'
        },
        doh: {
            title: 'Secure DNS (DoH)',
            description: 'Enable DNS over HTTPS to prevent DNS poisoning.',
            enable: 'Enable DoH Server',
            activeUrl: 'Active Resolver URL',
            subdomain: 'DNS Subdomain',
            createButton: 'Deploy Resolver',
            creatingButton: 'Deploying...',
            deactivate: 'Deactivate',
            copy: 'Copy URL',
            copied: 'Copied!',
            status: { creating: 'Deploying', failed: 'Failed', inactive: 'Inactive' }
        },
        iap: {
            title: 'Identity-Aware Proxy (IAP)',
            description: 'Use Google Cloud IAP for tunneling without public IP.',
            form: { projectId: 'Project ID', zone: 'Zone', instance: 'Instance Name' },
            info: { secure: 'Zero Trust', noPublicIp: 'No Public IP', tcpFwd: 'TCP Forwarding' },
            command: { title: 'Client Command', description: 'Run on client machine:', copy: 'Copy', copied: 'Copied' }
        },
        nat: {
            title: 'NAT Traversal',
            description: 'Techniques to bypass restrictive NATs and Firewalls.',
            status: 'Traversal Status',
            detectionBtn: 'Detect NAT Type',
            modes: { 
                stun: 'STUN (P2P)', stunDesc: 'Direct connection using UDP hole punching.',
                turn: 'TURN (Relay)', turnDesc: 'Relayed connection when P2P fails.',
                reverse: 'Reverse Tunnel', reverseDesc: 'Outbound connection to relay server.'
            },
            stunServer: 'STUN Server',
            turnServer: 'TURN Server',
            turnUser: 'TURN User',
            turnPass: 'TURN Password',
            keepAlive: 'Keep-Alive (Sec)',
            warning: 'TURN requires an external relay server.',
            holePunching: 'Enable UDP Hole Punching',
            save: 'Save Configuration'
        },
        sshSettings: {
            title: 'SSH Tunnels',
            description: 'Manage Local (-L) and Remote (-R) port forwarding rules.',
            localTitle: 'Local Forwarding (-L)',
            localDesc: 'Access remote services locally.',
            remoteTitle: 'Remote Forwarding (-R)',
            remoteDesc: 'Expose local services remotely.',
            bindPort: 'Bind Port',
            target: 'Target (host:port)',
            addRule: 'Add Rule',
            useCase: 'Common Use Cases'
        }
    },
    login: {
      title: 'Sanction Bypass Management',
      adminUser: 'Admin Username',
      placeholderUser: 'Enter username',
      passphrase: 'Password',
      placeholderPass: 'Enter password',
      error: 'Invalid credentials.',
      authenticate: 'Login',
      statusLabel: 'System Status',
      forgotPassword: { title: 'Password Recovery', description: 'Enter your admin email to receive a reset link.', forgotLink: 'Forgot Password?', sendButton: 'Send Reset Link', backToLogin: 'Back to Login', successTitle: 'Link Sent', successMessage: 'A password reset link has been sent to your email.' }
    },
    notFound: { title: '404', desc: 'Page not found.', home: 'Return Home' },
    terms: {
        title: 'Terms of Service',
        intro: 'By using this service, you agree to the following terms:',
        law1: '1. This service is strictly for bypassing unfair sanctions against Iranian professionals (Devs, Traders).',
        law2: '2. Access to pornographic content, gambling sites, and anti-Iran media is blocked and monitored.',
        law3: '3. Any attempt to use this service for cyber-attacks or illegal activities will result in immediate termination.',
        law4: '4. The user accepts full responsibility for their traffic.',
        accept: 'I Accept'
    },
    dashboard: {
      userBase: 'Users', totalUsers: 'Total', liveConnections: 'Active Connections', tunnelEstablished: 'Tunnels', totalData: 'Data Usage', encryptedPayload: 'Encrypted Traffic', simulatedTraffic: 'Throughput', networkHealth: 'Health', connectionQuality: 'Quality', packetLoss: 'Packet Loss', jitter: 'Jitter', stabilityChart: 'Stability', systemLogs: 'System Logs', geoDist: { title: 'Geo Distribution', users: 'users' }, active: 'Active', expired: 'Expired', banned: 'Banned', used: 'Used', remaining: 'Free', optimalDns: 'Optimal DNS', avgRTT: 'Avg RTT', tlsActive: 'TLS 1.3', tlsInactive: 'No TLS', camouflage: { title: 'Camouflage', jobStatus: 'Status', running: 'Running', idle: 'Idle', lastRun: 'Last Run', never: 'Never' }, quality: { Excellent: 'Excellent', Good: 'Good', Fair: 'Fair', Poor: 'Poor' }
    },
    users: { title: 'User Management', addUser: 'Add User', usage: 'Usage', expiry: 'Expiry', manageLinks: 'Links', addModal: { title: 'Create User', quota: 'Quota (GB)', expiry: 'Expiry (Days)' } },
    edgeStatus: { title: 'Edge Node Status', connectionTitle: 'Tunnel Status', statusLabel: 'Status', statusConnected: 'Connected', activeTunnel: 'Active Protocol' },
    camouflageSite: { title: 'AI Research Lab', navHome: 'Home', navApi: 'API', navContact: 'Contact', login: 'Portal', signup: 'Request Access', status: 'System Status', statusIdle: 'Operational', statusRunningAI: 'Training Models', statusRunningData: 'Syncing Data', statusRunningMedia: 'Fetching Assets', getStarted: 'Start Research', footer: '© 2024 AI Research Institute. All rights reserved.' },
    signup: { title: 'Request Access', description: 'Submit your details for review.', successTitle: 'Received', successMessage: 'Your request is under review.', backButton: 'Back', form: { name: 'Full Name', email: 'Email Address', reason: 'Usage Reason', submit: 'Submit Request' } },
    header: { systemSecure: 'Secured', edgeNode: { connected: 'Connected', connecting: 'Connecting', failed: 'Failed', notConfigured: 'No Config' } },
    view: { dashboard: 'Dashboard', users: 'Users', settings: 'Settings' }
  },
  fa: {
    common: {
      cancel: 'لغو',
      active: 'فعال',
      expired: 'منقضی',
      banned: 'مسدود',
      saveChanges: 'ذخیره تغییرات',
      username: 'نام کاربری',
      status: 'وضعیت',
      actions: 'عملیات',
      create: 'ایجاد',
      delete: 'حذف',
      price: 'قیمت',
      currency: 'واحد پول',
      duration: 'مدت',
      traffic: 'حجم',
      buy: 'خرید سرویس',
      email: 'ایمیل',
      telegram: 'آیدی تلگرام',
      pay: 'پرداخت آنلاین',
      gateway: 'درگاه بانکی',
      subLink: 'لینک اشتراک',
      copy: 'کپی',
      copied: 'کپی شد!',
      trackId: 'کد رهگیری',
      back: 'بازگشت',
      close: 'بستن',
      next: 'مرحله بعد',
      download: 'دانلود برنامه',
      recommendedApps: 'برنامه‌های پیشنهادی'
    },
    nav: {
      signOut: 'خروج',
      dashboard: 'داشبورد',
      users: 'کاربران',
      settings: 'تنظیمات',
      system: 'وضعیت سرور',
      store: 'فروشگاه',
      disk: 'فضای دیسک'
    },
    wizard: {
      title: 'نصب و راه‌اندازی',
      branding: {
          title: 'هویت بصری',
          description: 'عنوان و لوگوی پنل را تنظیم کنید.',
          siteTitle: 'عنوان سایت',
          logoUrl: 'آدرس لوگو (اختیاری)'
      },
      role: { title: 'نقش سرور', description: 'نقش این سرور را مشخص کنید.', germany: 'سرور خارج (Upstream)', germanyDesc: 'دیتاسنتر خارجی. تولید کننده کلید اتصال.', iran: 'سرور ایران (Edge)', iranDesc: 'دیتاسنتر داخلی. مصرف کننده کلید.', next: 'مرحله بعد' },
      external: {
         genKeyTitle: 'تولید کلید اتصال',
         genKeyDesc: 'این توکن را کپی کنید. برای اتصال سرور ایران به این سرور، باید این توکن را در ویزارد سرور ایران وارد کنید.',
         tokenLabel: 'توکن اتصال',
         genKeyNote: 'این توکن حاوی آدرس سرور و کلید امنیتی است.'
      },
      iran: {
         enterKeyTitle: 'اتصال به سرور خارج',
         enterKeyDesc: 'توکن اتصال تولید شده در سرور خارج را اینجا وارد کنید.',
         keyLabel: 'توکن اتصال',
         placeholder: 'EL-LINK-...',
         verifyBtn: 'بررسی اتصال',
         verified: 'ارتباط با سرور خارج برقرار شد'
      },
      finish: { doneButton: 'اتمام نصب' }
    },
    // ... existing translations ...
    store: {
      title: 'تعرفه‌ها',
      heroTitle: 'دسترسی پایدار به سرویس‌های تحریمی',
      heroDesc: 'راهکار قانونی و پایدار برای توسعه‌دهندگان، تریدرها و فریلنسرها جهت عبور از تحریم‌های ظالمانه.',
      bestValue: 'پیشنهاد ویژه',
      checkoutTitle: 'فاکتور پرداخت',
      contactInfo: 'اطلاعات تماس',
      paymentMethod: 'انتخاب درگاه',
      processing: 'در حال اتصال به بانک...',
      successTitle: 'تراکنش موفق',
      successDesc: 'سرویس شما با موفقیت فعال شد.',
      failTitle: 'تراکنش ناموفق',
      failDesc: 'پرداخت انجام نشد. لطفا مجددا تلاش کنید.',
      retry: 'تلاش مجدد',
      sanctionedApps: 'پشتیبانی از سرویس‌های',
      compliance: 'این سامانه منطبق بر قوانین جمهوری اسلامی ایران فعالیت می‌کند.',
      noIllegal: 'دسترسی به محتوای غیراخلاقی، سایت‌های شرط‌بندی و سایت‌های معاند مسدود می‌باشد.',
      buy: 'خرید پکیج'
    },
    settings: {
      title: 'تنظیمات سیستم',
      tabs: { general: 'عمومی', store: 'فروشگاه', branding: 'برندینگ', network: 'شبکه', security: 'امنیت', installer: 'نصاب', integrations: 'یکپارچه‌سازی' },
      credentials: { title: 'اطلاعات مدیر', newUser: 'نام کاربری جدید', newPass: 'رمز عبور جدید', success: 'ذخیره شد.' },
      branding: { title: 'شخصی‌سازی', name: 'نام برند', logo: 'آدرس لوگو', preview: 'پیش‌نمایش', saveSuccess: 'برندینگ ذخیره شد.' },
      telegram: {
          title: 'ربات تلگرام',
          description: 'مدیریت کاربران و ارسال نوتیفیکیشن از طریق تلگرام.',
          token: 'توکن ربات',
          adminId: 'شناسه عددی ادمین',
          enableBot: 'فعالسازی ربات',
          enableProxy: 'ارسال درخواست از طریق سرور خارج',
          test: 'تست اتصال',
          testing: 'در حال تست...',
          testSuccess: 'اتصال موفق بود!',
          testFail: 'اتصال برقرار نشد. لاگ‌ها را بررسی کنید.',
          instructionsTitle: 'راهنمای دریافت مشخصات:',
          instructions1: '۱. برای دریافت <strong class="text-white">توکن</strong>، به ربات <a href="https://t.me/BotFather" target="_blank" class="text-blue-400 underline">@BotFather</a> در تلگرام پیام داده و یک ربات جدید بسازید.',
          instructions2: '۲. برای دریافت <strong class="text-white">شناسه عددی</strong> خود، به ربات <a href="https://t.me/userinfobot" target="_blank" class="text-blue-400 underline">@userinfobot</a> پیام دهید.',
          proxyNoteTitle: 'نکته مهم',
          proxyNote: 'از آنجایی که تلگرام در منطقه شما فیلتر است، گزینه ارسال پراکسی باید فعال باشد تا ارتباط با سرورهای تلگرام از طریق سرور خارج انجام شود.'
      },
      domain: { 
          title: 'دامنه و SSL', 
          description: 'تنظیم دامنه اختصاصی برای لینک‌های اشتراک.', 
          saveSuccess: 'تنظیمات دامنه ذخیره شد.',
          domainName: 'نام دامنه',
          domainPlaceholder: 'example.com',
          subscriptionDomain: 'زیردامنه اشتراک',
          subscriptionDomainDesc: 'اختیاری. مثال: "sub".',
          subscriptionDomainPlaceholder: 'sub',
          invalidDomainError: 'فرمت دامنه نامعتبر است',
          instructionsTitle: 'راهنما',
          instructions: '۱. رکورد A دامنه خود را به آی‌پی سرور متصل کنید.\n۲. دکمه دریافت گواهی را بزنید.',
          healthCheckTitle: 'سلامت دامنه',
          pruneBtn: 'پاکسازی لیست',
          checkHealthBtn: 'بررسی سلامت',
          checkingHealthBtn: 'در حال بررسی...',
          status: { untested: 'بررسی نشده', testing: 'در حال تست', healthy: 'سالم', filtered: 'فیلتر شده' },
          certPath: 'مسیر گواهی (Cert)',
          keyPath: 'مسیر کلید (Key)',
          getCertButton: 'دریافت گواهی SSL رایگان',
          gettingCertButton: 'در حال درخواست از Let\'s Encrypt...',
          getCertSuccess: 'گواهی SSL با موفقیت نصب شد.',
          getCertError: 'خطا در دریافت گواهی. DNS را چک کنید.'
      },
      endpoint: {
          title: 'استراتژی تونل',
          description: 'انتخاب بهترین مسیر بر اساس شرایط شبکه.',
          blockchain: 'رله بلاک‌چین',
          blockchainDesc: 'مسیردهی غیرمتمرکز.',
          applyButton: 'اعمال استراتژی',
          success: 'استراتژی با موفقیت اعمال شد.'
      },
      camouflage: {
          title: 'استتار ترافیک',
          description: 'شبیه‌سازی الگوی ترافیک عادی برای جلوگیری از شناسایی.',
          profile: 'پروفایل ترافیک',
          profileDesc: { ai: 'آموزش مدل هوش مصنوعی', data: 'همگام‌سازی دیتابیس', media: 'استریم ویدیو' },
          frequency: 'فرکانس چرخش',
          lessFrequent: 'پایدار',
          moreFrequent: 'پویا',
          status: 'وضعیت موتور'
      },
      appCamouflage: {
          title: 'استتار لایه اپلیکیشن',
          description: 'جا زدن ترافیک به عنوان بازی‌های آنلاین محبوب.',
          enable: 'فعالسازی شبیه‌ساز پروتکل بازی',
          profile: 'پروفایل بازی',
          codm: 'کال آو دیوتی موبایل',
          codmDesc: 'شبیه‌سازی UDP/443',
          pubg: 'پابجی موبایل',
          pubgDesc: 'شبیه‌سازی UDP/10000+',
          clash: 'کلش رویال',
          clashDesc: 'شبیه‌سازی TCP/9339',
          mmorpg: 'بازی‌های نقش‌آفرینی',
          mmorpgDesc: 'ترکیبی TCP/UDP',
          liveStatus: 'وضعیت زنده'
      },
      doh: {
          title: 'DNS امن (DoH)',
          description: 'فعالسازی DNS بر بستر HTTPS برای جلوگیری از شنود.',
          enable: 'فعالسازی سرور DoH',
          activeUrl: 'آدرس ریزالور فعال',
          subdomain: 'زیردامنه DNS',
          createButton: 'راه‌اندازی ریزالور',
          creatingButton: 'در حال ساخت...',
          deactivate: 'غیرفعال‌سازی',
          copy: 'کپی آدرس',
          copied: 'کپی شد!',
          status: { creating: 'در حال ساخت', failed: 'خطا', inactive: 'غیرفعال' }
      },
      iap: {
          title: 'پروکسی هویت‌محور (IAP)',
          description: 'استفاده از تونل گوگل (IAP) بدون نیاز به آی‌پی عمومی.',
          form: { projectId: 'شناسه پروژه', zone: 'منطقه (Zone)', instance: 'نام اینستنس' },
          info: { secure: 'Zero Trust', noPublicIp: 'بدون IP عمومی', tcpFwd: 'فوروارد TCP' },
          command: { title: 'دستور سمت کلاینت', description: 'این دستور را در سیستم کاربر اجرا کنید:', copy: 'کپی', copied: 'کپی شد' }
      },
      nat: {
          title: 'عبور از NAT',
          description: 'تکنیک‌های عبور از فایروال‌ها و NAT های سخت‌گیرانه.',
          status: 'وضعیت عبور',
          detectionBtn: 'تشخیص نوع NAT',
          modes: { 
              stun: 'STUN (P2P)', stunDesc: 'اتصال مستقیم با UDP Hole Punching.',
              turn: 'TURN (Relay)', turnDesc: 'استفاده از سرور واسط (Relay).',
              reverse: 'تونل معکوس', reverseDesc: 'اتصال خروجی به سرور واسط.'
          },
          stunServer: 'سرور STUN',
          turnServer: 'سرور TURN',
          turnUser: 'نام کاربری TURN',
          turnPass: 'رمز عبور TURN',
          keepAlive: 'فاصله Keep-Alive (ثانیه)',
          warning: 'حالت TURN نیاز به سرور واسط خارجی دارد.',
          holePunching: 'فعالسازی UDP Hole Punching',
          save: 'ذخیره تنظیمات'
      },
      sshSettings: {
          title: 'تونل‌های SSH',
          description: 'مدیریت پورت فورواردینگ محلی (-L) و ریموت (-R).',
          localTitle: 'فوروارد محلی (-L)',
          localDesc: 'دسترسی به سرویس‌های ریموت در لوکال.',
          remoteTitle: 'فوروارد ریموت (-R)',
          remoteDesc: 'در دسترس قرار دادن سرویس لوکال در ریموت.',
          bindPort: 'پورت Bind',
          target: 'مقصد (host:port)',
          addRule: 'افزودن قانون',
          useCase: 'موارد استفاده'
      }
    },
    login: {
      title: 'سامانه مدیریت عبور از تحریم',
      adminUser: 'نام کاربری',
      placeholderUser: 'نام کاربری را وارد کنید',
      passphrase: 'رمز عبور',
      placeholderPass: 'رمز عبور را وارد کنید',
      error: 'اطلاعات اشتباه است.',
      authenticate: 'ورود به پنل',
      statusLabel: 'وضعیت سامانه',
      forgotPassword: { title: 'بازیابی رمز عبور', description: 'ایمیل ادمین را وارد کنید تا لینک بازیابی ارسال شود.', forgotLink: 'فراموشی رمز؟', sendButton: 'ارسال لینک', backToLogin: 'بازگشت به ورود', successTitle: 'لینک ارسال شد', successMessage: 'لینک بازیابی رمز عبور به ایمیل شما ارسال شد.' }
    },
    notFound: { title: '۴۰۴', desc: 'صفحه یافت نشد.', home: 'خانه' },
    terms: {
        title: 'قوانین و مقررات',
        intro: 'استفاده از این سرویس به منزله پذیرش قوانین زیر است:',
        law1: '۱. این سرویس صرفاً جهت دور زدن تحریم‌های خارجی علیه متخصصین ایرانی ارائه می‌شود.',
        law2: '۲. دسترسی به محتوای غیراخلاقی، سایت‌های شرط‌بندی و شبکه‌های معاند مسدود است.',
        law3: '۳. هرگونه استفاده جهت حملات سایبری یا کلاهبرداری ممنوع است.',
        law4: '۴. مسئولیت استفاده از سرویس بر عهده کاربر است.',
        accept: 'می‌پذیرم'
    },
    dashboard: {
      userBase: 'کاربران', totalUsers: 'کل', liveConnections: 'اتصالات فعال', tunnelEstablished: 'تونل‌ها', totalData: 'ترافیک کل', encryptedPayload: 'ترافیک رمزنگاری', simulatedTraffic: 'نرخ انتقال', networkHealth: 'سلامت شبکه', connectionQuality: 'کیفیت', packetLoss: 'پکت لاس', jitter: 'جیتر', stabilityChart: 'پایداری', systemLogs: 'لاگ سیستم', geoDist: { title: 'توزیع جغرافیایی', users: 'کاربر' }, active: 'فعال', expired: 'منقضی', banned: 'مسدود', used: 'مصرفی', remaining: 'باقی‌مانده', optimalDns: 'DNS بهینه', avgRTT: 'پینگ', tlsActive: 'TLS فعال', tlsInactive: 'TLS غیرفعال', camouflage: { title: 'وضعیت استتار', jobStatus: 'وضعیت', running: 'در حال اجرا', idle: 'آماده‌باش', lastRun: 'آخرین اجرا', never: 'هرگز' }, quality: { Excellent: 'عالی', Good: 'خوب', Fair: 'متوسط', Poor: 'ضعیف' }
    },
    users: { title: 'مدیریت کاربران', addUser: 'افزودن کاربر', usage: 'مصرف', expiry: 'انقضا', manageLinks: 'لینک‌ها', addModal: { title: 'کاربر جدید', quota: 'حجم (گیگ)', expiry: 'انقضا (روز)' } },
    edgeStatus: { title: 'وضعیت سرور ایران', connectionTitle: 'وضعیت تونل', statusLabel: 'وضعیت', statusConnected: 'متصل', activeTunnel: 'پروتکل فعال' },
    camouflageSite: { title: 'پژوهشکده هوش مصنوعی', navHome: 'خانه', navApi: 'API', navContact: 'تماس', login: 'پرتال', signup: 'درخواست', status: 'وضعیت', statusIdle: 'عملیاتی', statusRunningAI: 'آموزش مدل', statusRunningData: 'همگام‌سازی', statusRunningMedia: 'دریافت مدیا', getStarted: 'شروع پژوهش', footer: '© ۱۴۰۳ تمامی حقوق محفوظ است.' },
    signup: { title: 'ثبت‌نام', description: 'اطلاعات خود را وارد کنید.', successTitle: 'دریافت شد', successMessage: 'درخواست شما بررسی می‌شود.', backButton: 'بازگشت', form: { name: 'نام و نام خانوادگی', email: 'ایمیل', reason: 'مورد مصرف', submit: 'ارسال درخواست' } },
    header: { systemSecure: 'ایمن', edgeNode: { connected: 'متصل', connecting: 'در حال اتصال', failed: 'قطع', notConfigured: 'تنظیم نشده' } },
    view: { dashboard: 'داشبورد', users: 'کاربران', settings: 'تنظیمات' }
  }
};
