
export const translations: any = {
  en: {
    common: { 
      cancel: 'Cancel', active: 'Active', expired: 'Expired', banned: 'Banned', 
      saveChanges: 'Save Changes', username: 'Username', status: 'Status', 
      actions: 'Actions', create: 'Create', delete: 'Delete', price: 'Price', 
      currency: 'Currency', duration: 'Duration', traffic: 'Traffic', buy: 'Purchase', 
      email: 'Email', pay: 'Pay Now', gateway: 'Gateway', subLink: 'Subscription Link', 
      copy: 'Copy', copied: 'Copied!', telegram: 'Telegram ID', trackId: 'Tracking ID',
      back: 'Back', close: 'Close', next: 'Next', download: 'Download', recommendedApps: 'Recommended Apps',
      deleteConfirm: 'Are you sure you want to delete user'
    },
    nav: { 
      signOut: 'Sign Out', dashboard: 'Dashboard', users: 'Users', 
      settings: 'Settings', system: 'System Status', store: 'Store Admin', 
      disk: 'Disk Usage' 
    },
    wizard: {
      title: 'Installation Wizard',
      branding: {
          title: 'Brand Identity',
          description: 'Configure the look and feel of your panel.',
          siteTitle: 'Site Title',
          logoUrl: 'Upload Logo (Optional)'
      },
      role: { title: 'Server Role', description: 'Select the role of this server.', germany: 'Upstream (Foreign)', germanyDesc: 'Located outside Iran. Generates connection keys.', iran: 'Edge (Iran)', iranDesc: 'Located inside Iran. Connects to Upstream.', next: 'Next Step' },
      external: {
         genKeyTitle: 'Generate Connection Key',
         genKeyDesc: 'Copy this token. You will need to paste it into your Iran Server setup wizard to link them.',
         tokenLabel: 'Connection Token',
         genKeyNote: 'This token contains your server IP and Auth Key.'
      },
      iran: {
         enterKeyTitle: 'Connect to Upstream',
         enterKeyDesc: 'Paste the Connection Token generated by your External (Foreign) server here.',
         keyLabel: 'Connection Token',
         placeholder: 'EL-LINK-...',
         verifyBtn: 'Verify Connection',
         verified: 'Upstream Verified',
         invalidToken: 'Invalid or expired connection token.',
         lockoutTitle: 'Too Many Failed Attempts',
         lockoutMessage: 'For security, you have been locked out. Please try again in {{minutes}} minutes.'
      },
      finish: { doneButton: 'Finish Installation' }
    },
    upstream: {
        donateButton: 'Donate Server (Share Key)',
        donateDesc: 'This opens your device\'s share dialog to send the key to someone in a restricted region.'
    },
    store: {
      title: 'Service Plans',
      heroTitle: 'Secure Access to International Services',
      heroDesc: 'Legal and stable solution for Developers, Traders, and Freelancers to bypass unfair sanctions.',
      bestValue: 'Best Value',
      checkoutTitle: 'Checkout',
      contactInfo: 'Contact Information',
      paymentMethod: 'Select Payment Gateway',
      processing: 'Connecting to Gateway...',
      successTitle: 'Payment Successful',
      successDesc: 'Service activated successfully. Your connection details are below.',
      failTitle: 'Payment Failed',
      failDesc: 'Transaction was rejected. Please try again.',
      retry: 'Try Again',
      sanctionedApps: 'Optimized For',
      compliance: 'Operating under the regulations of the Islamic Republic of Iran.',
      noIllegal: 'Access to immoral content, gambling, and anti-state media is strictly blocked.',
      buy: 'Purchase Plan'
    },
    settings: {
        title: 'System Settings',
        tabs: { general: 'General', store: 'Store & Plans', branding: 'Branding', network: 'Network', security: 'Security', installer: 'Installer', integrations: 'Integrations', roadmap: 'Roadmap' },
        credentials: { title: 'Admin Credentials', newUser: 'New Username', newPass: 'New Password', success: 'Credentials updated successfully.' },
        branding: { title: 'Branding', name: 'Brand Name', logo: 'Logo URL / Upload', preview: 'Preview', saveSuccess: 'Branding updated.' },
        storeMgmt: { title: 'Store Configuration', currency: 'Currency Unit', gateways: 'Payment Gateways', merchant: 'Merchant ID / Token', packages: 'Service Packages', edit: 'Edit', save: 'Save' },
        security: {
            tfa: {
                title: 'Two-Factor Authentication (2FA)',
                description: 'Add an extra layer of security to your admin account using a time-based one-time password (TOTP) application.',
                enable: 'Enable 2FA',
                disable: 'Disable 2FA',
                step1: '1. Scan this QR Code',
                step1Desc: 'Scan this image with an authenticator app like Google Authenticator, Authy, or 1Password.',
                step2: '2. Or Enter Key Manually',
                step2Desc: 'If you cannot scan the QR code, you can manually enter this secret key into your authenticator app.',
                step3: '3. Verify Code',
                step3Desc: 'Enter the 6-digit code from your app to confirm setup.',
                verifyButton: 'Verify & Activate',
                verifying: 'Verifying...',
                success: '2FA enabled successfully!',
                fail: 'Invalid code. Please try again.',
                enterCode: 'Enter 6-digit code'
            }
        },
        telegram: {
            title: 'Telegram Bot',
            description: 'Manage users and send notifications via Telegram.',
            token: 'Bot Token',
            adminId: 'Admin Chat ID',
            enableBot: 'Enable Bot',
            enableProxy: 'Route API through Foreign Server',
            test: 'Test Connection',
            testing: 'Testing...',
            testSuccess: 'Connection successful!',
            testFail: 'Connection failed. Check logs.',
            instructionsTitle: 'How to get your credentials:',
            instructions1: '1. Talk to <a href="https://t.me/BotFather" target="_blank" class="text-blue-400 underline">@BotFather</a> on Telegram and create a new bot to get your <strong class="text-white">Token</strong>.',
            instructions2: '2. Talk to <a href="https://t.me/userinfobot" target="_blank" class="text-blue-400 underline">@userinfobot</a> to get your numerical <strong class="text-white">Chat ID</strong>.',
            proxyNoteTitle: 'Important Note',
            proxyNote: 'Because Telegram is blocked in your region, you MUST keep the proxy option enabled to communicate with the API via your foreign server.'
        },
        domain: { 
            title: 'Domain & SSL', 
            description: 'Configure your custom domain for subscription links.', 
            saveSuccess: 'Domain saved.',
            domainName: 'Domain Name',
            domainPlaceholder: 'example.com',
            subscriptionDomain: 'Subscription Subdomain',
            subscriptionDomainDesc: 'Optional. e.g., "sub".',
            subscriptionDomainPlaceholder: 'sub',
            invalidDomainError: 'Invalid domain format',
            instructionsTitle: 'Instructions',
            instructions: '1. Point your domain A record to this server IP.\n2. Click "Get Certificate" to generate SSL.',
            healthCheckTitle: 'Domain Health',
            pruneBtn: 'Prune List',
            checkHealthBtn: 'Check Health',
            checkingHealthBtn: 'Checking...',
            status: { untested: 'Untested', testing: 'Testing', healthy: 'Healthy', filtered: 'Filtered' },
            certPath: 'Certificate Path',
            keyPath: 'Private Key Path',
            getCertButton: 'Get Free SSL Certificate',
            gettingCertButton: 'Requesting Let\'s Encrypt...',
            getCertSuccess: 'SSL Certificate installed successfully.',
            getCertError: 'Failed to get certificate. Check DNS.'
        },
        endpoint: {
            title: 'Tunnel Strategy',
            description: 'Select the optimal routing strategy based on network conditions.',
            blockchain: 'Blockchain Relay',
            blockchainDesc: 'Decentralized routing.',
            applyButton: 'Apply Strategy',
            success: 'Strategy applied successfully.'
        },
        camouflage: {
            title: 'Traffic Camouflage',
            description: 'Mimic legitimate traffic patterns to evade detection.',
            profile: 'Traffic Profile',
            profileDesc: { ai: 'AI Model Training', data: 'Database Sync', media: 'Video Streaming' },
            frequency: 'Rotation Frequency',
            lessFrequent: 'Stable',
            moreFrequent: 'Dynamic',
            status: 'Engine Status'
        },
        appCamouflage: {
            title: 'Application Layer Camouflage',
            description: 'Masquerade traffic as popular game protocols.',
            enable: 'Enable Game Protocol Emulation',
            profile: 'Game Profile',
            codm: 'Call of Duty Mobile',
            codmDesc: 'UDP/443 Emulation',
            pubg: 'PUBG Mobile',
            pubgDesc: 'UDP/10000+ Emulation',
            clash: 'Clash Royale',
            clashDesc: 'TCP/9339 Emulation',
            mmorpg: 'Generic MMORPG',
            mmorpgDesc: 'Mixed TCP/UDP',
            liveStatus: 'Live Status'
        },
        doh: {
            title: 'Secure DNS (DoH)',
            description: 'Enable DNS over HTTPS to prevent DNS poisoning.',
            enable: 'Enable DoH Server',
            activeUrl: 'Active Resolver URL',
            subdomain: 'DNS Subdomain',
            createButton: 'Deploy Resolver',
            creatingButton: 'Deploying...',
            deactivate: 'Deactivate',
            copy: 'Copy URL',
            copied: 'Copied!',
            status: { creating: 'Deploying', failed: 'Failed', inactive: 'Inactive' }
        },
        iap: {
            title: 'Identity-Aware Proxy (IAP)',
            description: 'Use Google Cloud IAP for tunneling without public IP.',
            form: { projectId: 'Project ID', zone: 'Zone', instance: 'Instance Name' },
            info: { secure: 'Zero Trust', noPublicIp: 'No Public IP', tcpFwd: 'TCP Forwarding' },
            command: { title: 'Client Command', description: 'Run on client machine:', copy: 'Copy', copied: 'Copied' }
        },
        nat: {
            title: 'NAT Traversal',
            description: 'Techniques to bypass restrictive NATs and Firewalls.',
            status: 'Traversal Status',
            detectionBtn: 'Detect NAT Type',
            modes: { 
                stun: 'STUN (P2P)', stunDesc: 'Direct connection using UDP hole punching.',
                turn: 'TURN (Relay)', turnDesc: 'Relayed connection when P2P fails.',
                reverse: 'Reverse Tunnel', reverseDesc: 'Outbound connection to relay server.'
            },
            stunServer: 'STUN Server',
            turnServer: 'TURN Server',
            turnUser: 'TURN User',
            turnPass: 'TURN Password',
            keepAlive: 'Keep-Alive (Sec)',
            warning: 'TURN requires an external relay server.',
            holePunching: 'Enable UDP Hole Punching',
            save: 'Save Configuration'
        },
        sshSettings: {
            title: 'SSH Tunnels',
            description: 'Manage Local (-L) and Remote (-R) port forwarding rules.',
            localTitle: 'Local Forwarding (-L)',
            localDesc: 'Access remote services locally.',
            remoteTitle: 'Remote Forwarding (-R)',
            remoteDesc: 'Expose local services remotely.',
            bindPort: 'Bind Port',
            target: 'Target (host:port)',
            addRule: 'Add Rule',
            useCase: 'Common Use Cases'
        }
    },
    login: {
      title: 'Sanction Bypass Management',
      adminUser: 'Admin Username',
      placeholderUser: 'Enter username',
      passphrase: 'Password',
      placeholderPass: 'Enter password',
      error: 'Invalid credentials.',
      authenticate: 'Login',
      statusLabel: 'System Status',
      tfaTitle: 'Two-Factor Authentication',
      tfaDescription: 'Enter the 6-digit code from your authenticator app.',
      tfaPlaceholder: '123456',
      verify: 'Verify',
      forgotPassword: { title: 'Password Recovery', description: 'Enter your admin email to receive a reset link.', forgotLink: 'Forgot Password?', sendButton: 'Send Reset Link', backToLogin: 'Back to Login', successTitle: 'Link Sent', successMessage: 'A password reset link has been sent to your email.' }
    },
    notFound: { title: '404', desc: 'Page not found.', home: 'Return Home' },
    terms: {
        title: 'Terms of Service',
        intro: 'By using this service, you agree to the following terms:',
        law1: '1. This service is strictly for bypassing unfair sanctions against Iranian professionals (Devs, Traders).',
        law2: '2. Access to pornographic content, gambling sites, and anti-Iran media is blocked and monitored.',
        law3: '3. Any attempt to use this service for cyber-attacks or illegal activities will result in immediate termination.',
        law4: '4. The user accepts full responsibility for their traffic.',
        accept: 'I Accept'
    },
    dashboard: {
      userBase: 'Users', totalUsers: 'Total', liveConnections: 'Active Connections', tunnelEstablished: 'Tunnels', totalData: 'Data Usage', encryptedPayload: 'Encrypted Traffic', simulatedTraffic: 'Throughput', networkHealth: 'Health', connectionQuality: 'Quality', packetLoss: 'Packet Loss', jitter: 'Jitter', stabilityChart: 'Stability', systemLogs: 'System Logs', geoDist: { title: 'Geo Distribution', users: 'users' }, active: 'Active', expired: 'Expired', banned: 'Banned', used: 'Used', remaining: 'Free', optimalDns: 'Optimal DNS', avgRTT: 'Avg RTT', tlsActive: 'TLS 1.3', tlsInactive: 'No TLS', camouflage: { title: 'Camouflage', jobStatus: 'Status', running: 'Running', idle: 'Idle', lastRun: 'Last Run', never: 'Never' }, quality: { Excellent: 'Excellent', Good: 'Good', Fair: 'Fair', Poor: 'Poor' },
      ai: {
          analyze: 'Analyze with AI',
          analyzing: 'Analyzing...',
          analysisTitle: 'AI Log Analysis',
          analysisError: 'Could not get analysis from AI.'
      },
      protocols: {
          title: 'Protocol Usage'
      }
    },
    users: { 
        title: 'User Management', addUser: 'Add User', usage: 'Usage', expiry: 'Expiry', manageLinks: 'Links', addModal: { title: 'Create User', quota: 'Quota (GB)', expiry: 'Expiry (Days)' },
        bulk: {
            actions: 'Bulk Actions',
            delete: 'Delete Selected',
            extend: 'Extend Expiry',
            addQuota: 'Add Quota',
            selected: 'selected'
        }
    },
    tunnel: {
      title: 'Tunnel Optimization',
      description: 'Automatically or manually select the best connection path between your Iran and Foreign servers.',
      autoPilot: 'Auto-Pilot',
      manual: 'Manual',
      nextTest: 'Next test in',
      disabled: 'Auto-test is disabled',
      analyzing: 'Analyzing...',
      testNow: 'Test Paths',
      failed: 'Failed',
      pinging: 'Pinging...',
      awaiting: 'Awaiting Test',
      activate: 'Activate'
    },
    edgeStatus: { title: 'Edge Node Status', connectionTitle: 'Tunnel Status', statusLabel: 'Status', statusConnected: 'Connected', activeTunnel: 'Active Protocol' },
    camouflageSite: { title: 'AI Research Lab', navHome: 'Home', navApi: 'API', navContact: 'Contact', login: 'Portal', signup: 'Request Access', status: 'System Status', statusIdle: 'Operational', statusRunningAI: 'Training Models', statusRunningData: 'Syncing Data', statusRunningMedia: 'Fetching Assets', getStarted: 'Start Research', footer: '© 2024 AI Research Institute. All rights reserved.' },
    signup: { title: 'Request Access', description: 'Submit your details for review.', successTitle: 'Received', successMessage: 'Your request is under review.', backButton: 'Back', form: { name: 'Full Name', email: 'Email Address', reason: 'Usage Reason', submit: 'Submit Request' } },
    header: { systemSecure: 'Secured', edgeNode: { connected: 'Connected', connecting: 'Connecting', failed: 'Failed', notConfigured: 'No Config' } },
    view: { dashboard: 'Dashboard', users: 'Users', settings: 'Settings' },
    tooltips: {
        dashboard: {
            userCard: 'An overview of your user base, categorized by their current status.',
            connectionsCard: 'The number of users currently connected and actively passing traffic through the tunnel.',
            dataCard: 'Total data transferred since the last server restart and the current real-time transfer rate.',
            trafficChart: 'This chart simulates real user traffic (blue) and camouflage traffic (green) to visualize network activity.'
        },
        settings: {
            domainName: 'Your primary domain. This is used to generate SSL certificates and for client connections. Make sure your A record points to this server\'s IP.',
            subscriptionDomain: 'An optional, separate domain for user subscription links. Useful for isolating user-facing pages from the main domain.',
            healthCheck: 'Tests a list of generated subdomains against DNS blocklists to find clean IPs. Useful for clients in heavily restricted networks.',
            getCert: 'Uses Let\'s Encrypt to automatically request and install a free, trusted SSL certificate for your domain.',
            endpointStrategy: 'Defines the underlying technology used for tunneling. CDN is best for obfuscation, while VPS offers the lowest latency.',
            tunnelOptimization: 'Manage how the system tests and selects the best connection path between your Iran and Foreign servers.',
            autoPilot: 'The system will automatically test all tunnels periodically and switch to the one with the best performance (lowest latency and jitter).',
            manualMode: 'You are in control. Manually test tunnels and choose which one to activate.',
            camouflageProfile: 'Changes the fake traffic pattern generated by the camouflage engine to better blend in with normal network traffic.',
            camouflageFrequency: 'How often the camouflage engine changes its traffic patterns. More frequent changes are harder to detect but may slightly increase server load.',
            appCamoEnable: 'When enabled, the system will attempt to disguise your traffic as a popular online game to bypass protocol-based filtering.',
            appCamoProfile: 'Select which game protocol to emulate. Each profile mimics the specific UDP/TCP packet behavior of that game.',
            dohEnable: 'Activates a DNS-over-HTTPS resolver on your server. Clients can use this to encrypt their DNS queries, preventing DNS poisoning and blocking.',
            dohSubdomain: 'The subdomain where the DoH resolver will be available (e.g., dns.yourdomain.com).',
            iap: 'Google Cloud\'s Identity-Aware Proxy allows you to create secure tunnels to your instances without needing a public IP address, enhancing security.',
        }
    },
    roadmap: {
        title: 'Future Development',
        description: 'Our team is constantly working on new features to enhance security, performance, and usability. Here are some of the exciting improvements on our horizon.',
        status: {
            researching: 'Researching',
            planned: 'Planned',
            in_progress: 'In Progress',
            beta: 'Beta'
        },
        items: [
            {
                title: 'AI-Powered Recommendations',
                description: 'Gemini will analyze user traffic patterns to suggest optimal server locations and protocols for new users.',
                status: 'in_progress'
            },
            {
                title: 'Automated Anomaly Detection',
                description: 'The system will automatically detect and flag unusual user activity, such as sudden high bandwidth usage, to prevent abuse.',
                status: 'planned'
            },
            {
                title: 'Dedicated Client Applications',
                description: 'A dedicated, cross-platform client application (Windows, macOS, Android, iOS) for one-click connections and seamless profile syncing.',
                status: 'planned'
            },
            {
                title: 'Decentralized Authentication',
                description: 'Integration with blockchain-based identity systems for enhanced privacy and censorship resistance.',
                status: 'researching'
            },
            {
                title: 'Dynamic Obfuscation Engine',
                description: 'The camouflage engine will learn from network traffic in real-time to create more convincing traffic patterns, adapting to network changes automatically.',
                status: 'researching'
            }
        ]
    }
  },
  fa: {
    common: {
      cancel: 'لغو',
      active: 'فعال',
      expired: 'منقضی',
      banned: 'مسدود',
      saveChanges: 'ذخیره تغییرات',
      username: 'نام کاربری',
      status: 'وضعیت',
      actions: 'عملیات',
      create: 'ایجاد',
      delete: 'حذف',
      price: 'قیمت',
      currency: 'واحد پول',
      duration: 'مدت',
      traffic: 'حجم',
      buy: 'خرید سرویس',
      email: 'ایمیل',
      telegram: 'آیدی تلگرام',
      pay: 'پرداخت آنلاین',
      gateway: 'درگاه بانکی',
      subLink: 'لینک اشتراک',
      copy: 'کپی',
      copied: 'کپی شد!',
      trackId: 'کد رهگیری',
      back: 'بازگشت',
      close: 'بستن',
      next: 'مرحله بعد',
      download: 'دانلود برنامه',
      recommendedApps: 'برنامه‌های پیشنهادی',
      deleteConfirm: 'آیا از حذف کاربر مطمئن هستید'
    },
    nav: {
      signOut: 'خروج',
      dashboard: 'داشبورد',
      users: 'کاربران',
      settings: 'تنظیمات',
      system: 'وضعیت سرور',
      store: 'فروشگاه',
      disk: 'فضای دیسک'
    },
    wizard: {
      title: 'نصب و راه‌اندازی',
      branding: {
          title: 'هویت بصری',
          description: 'عنوان و لوگوی پنل را تنظیم کنید.',
          siteTitle: 'عنوان سایت',
          logoUrl: 'آپلود لوگو (اختیاری)'
      },
      role: { title: 'نقش سرور', description: 'نقش این سرور را مشخص کنید.', germany: 'سرور خارج (Upstream)', germanyDesc: 'دیتاسنتر خارجی. تولید کننده کلید اتصال.', iran: 'سرور ایران (Edge)', iranDesc: 'دیتاسنتر داخلی. مصرف کننده کلید.', next: 'مرحله بعد' },
      external: {
         genKeyTitle: 'تولید کلید اتصال',
         genKeyDesc: 'این توکن را کپی کنید. برای اتصال سرور ایران به این سرور، باید این توکن را در ویزارد سرور ایران وارد کنید.',
         tokenLabel: 'توکن اتصال',
         genKeyNote: 'این توکن حاوی آدرس سرور و کلید امنیتی است.'
      },
      iran: {
         enterKeyTitle: 'اتصال به سرور خارج',
         enterKeyDesc: 'توکن اتصال تولید شده در سرور خارج را اینجا وارد کنید.',
         keyLabel: 'توکن اتصال',
         placeholder: 'EL-LINK-...',
         verifyBtn: 'بررسی اتصال',
         verified: 'ارتباط با سرور خارج برقرار شد',
         invalidToken: 'توکن اتصال نامعتبر یا منقضی شده است.',
         lockoutTitle: 'تعداد تلاش‌های ناموفق بیش از حد مجاز',
         lockoutMessage: 'به دلایل امنیتی، دسترسی شما موقتا مسدود شد. لطفا تا {{minutes}} دقیقه دیگر دوباره تلاش کنید.'
      },
      finish: { doneButton: 'اتمام نصب' }
    },
    upstream: {
        donateButton: 'اهدای سرور (اشتراک‌گذاری کلید)',
        donateDesc: 'با این دکمه می‌توانید کلید اتصال را از طریق منوی اشتراک‌گذاری دستگاه خود برای دیگران ارسال کنید.'
    },
    store: {
      title: 'تعرفه‌ها',
      heroTitle: 'دسترسی پایدار به سرویس‌های تحریمی',
      heroDesc: 'راهکار قانونی و پایدار برای توسعه‌دهندگان، تریدرها و فریلنسرها جهت عبور از تحریم‌های ظالمانه.',
      bestValue: 'پیشنهاد ویژه',
      checkoutTitle: 'فاکتور پرداخت',
      contactInfo: 'اطلاعات تماس',
      paymentMethod: 'انتخاب درگاه',
      processing: 'در حال اتصال به بانک...',
      successTitle: 'تراکنش موفق',
      successDesc: 'سرویس شما با موفقیت فعال شد.',
      failTitle: 'تراکنش ناموفق',
      failDesc: 'پرداخت انجام نشد. لطفا مجددا تلاش کنید.',
      retry: 'تلاش مجدد',
      sanctionedApps: 'پشتیبانی از سرویس‌های تحریم‌شده',
      compliance: 'این سامانه منطبق بر قوانین جمهوری اسلامی ایران فعالیت می‌کند.',
      noIllegal: 'دسترسی به محتوای غیراخلاقی، سایت‌های شرط‌بندی و سایت‌های معاند مسدود می‌باشد.',
      buy: 'خرید پکیج'
    },
    settings: {
      title: 'تنظیمات سیستم',
      tabs: { general: 'عمومی', store: 'فروشگاه', branding: 'برندینگ', network: 'شبکه', security: 'امنیت', installer: 'نصاب', integrations: 'یکپارچه‌سازی', roadmap: 'نقشه راه' },
      credentials: { title: 'اطلاعات مدیر', newUser: 'نام کاربری جدید', newPass: 'رمز عبور جدید', success: 'ذخیره شد.' },
      branding: { title: 'شخصی‌سازی', name: 'نام برند', logo: 'آدرس لوگو', preview: 'پیش‌نمایش', saveSuccess: 'برندینگ ذخیره شد.' },
      storeMgmt: { title: 'تنظیمات فروشگاه', currency: 'واحد پول', gateways: 'درگاه‌های پرداخت', merchant: 'مرچنت آیدی / توکن', packages: 'بسته‌های خدمات', edit: 'ویرایش', save: 'ذخیره' },
      security: {
            tfa: {
                title: 'احراز هویت دو مرحله‌ای (2FA)',
                description: 'با استفاده از یک برنامه احراز هویت (مانند Google Authenticator)، یک لایه امنیتی اضافی به حساب کاربری خود اضافه کنید.',
                enable: 'فعال‌سازی 2FA',
                disable: 'غیرفعال‌سازی 2FA',
                step1: '۱. اسکن کد QR',
                step1Desc: 'این تصویر را با برنامه احراز هویت خود اسکن کنید.',
                step2: '۲. یا ورود دستی کلید',
                step2Desc: 'اگر نمی‌توانید کد را اسکن کنید، این کلید را به صورت دستی در برنامه وارد کنید.',
                step3: '۳. تایید کد',
                step3Desc: 'کد ۶ رقمی از برنامه خود را برای تایید نهایی وارد کنید.',
                verifyButton: 'تایید و فعال‌سازی',
                verifying: 'در حال بررسی...',
                success: 'احراز هویت دو مرحله‌ای با موفقیت فعال شد!',
                fail: 'کد نامعتبر است. لطفا دوباره تلاش کنید.',
                enterCode: 'کد ۶ رقمی را وارد کنید'
            }
      },
      telegram: {
          title: 'ربات تلگرام',
          description: 'مدیریت کاربران و ارسال نوتیفیکیشن از طریق تلگرام.',
          token: 'توکن ربات',
          adminId: 'شناسه عددی ادمین',
          enableBot: 'فعالسازی ربات',
          enableProxy: 'ارسال درخواست از طریق سرور خارج',
          test: 'تست اتصال',
          testing: 'در حال تست...',
          testSuccess: 'اتصال موفق بود!',
          testFail: 'اتصال برقرار نشد. لاگ‌ها را بررسی کنید.',
          instructionsTitle: 'راهنمای دریافت مشخصات:',
          instructions1: '۱. برای دریافت <strong class="text-white">توکن</strong>، به ربات <a href="https://t.me/BotFather" target="_blank" class="text-blue-400 underline">@BotFather</a> در تلگرام پیام داده و یک ربات جدید بسازید.',
          instructions2: '۲. برای دریافت <strong class="text-white">شناسه عددی</strong> خود، به ربات <a href="https://t.me/userinfobot" target="_blank" class="text-blue-400 underline">@userinfobot</a> پیام دهید.',
          proxyNoteTitle: 'نکته مهم',
          proxyNote: 'از آنجایی که تلگرام در منطقه شما فیلتر است، گزینه ارسال پراکسی باید فعال باشد تا ارتباط با سرورهای تلگرام از طریق سرور خارج انجام شود.'
      },
      domain: { 
          title: 'دامنه و SSL', 
          description: 'تنظیم دامنه اختصاصی برای لینک‌های اشتراک.', 
          saveSuccess: 'تنظیمات دامنه ذخیره شد.',
          domainName: 'نام دامنه',
          domainPlaceholder: 'example.com',
          subscriptionDomain: 'زیردامنه اشتراک',
          subscriptionDomainDesc: 'اختیاری. مثال: "sub".',
          subscriptionDomainPlaceholder: 'sub',
          invalidDomainError: 'فرمت دامنه نامعتبر است',
          instructionsTitle: 'راهنما',
          instructions: '۱. رکورد A دامنه خود را به آی‌پی سرور متصل کنید.\n۲. دکمه دریافت گواهی را بزنید.',
          healthCheckTitle: 'سلامت دامنه',
          pruneBtn: 'پاکسازی لیست',
          checkHealthBtn: 'بررسی سلامت',
          checkingHealthBtn: 'در حال بررسی...',
          status: { untested: 'بررسی نشده', testing: 'در حال تست', healthy: 'سالم', filtered: 'فیلتر شده' },
          certPath: 'مسیر گواهی (Cert)',
          keyPath: 'مسیر کلید (Key)',
          getCertButton: 'دریافت گواهی SSL رایگان',
          gettingCertButton: 'در حال درخواست از Let\'s Encrypt...',
          getCertSuccess: 'گواهی SSL با موفقیت نصب شد.',
          getCertError: 'خطا در دریافت گواهی. DNS را چک کنید.'
      },
      endpoint: {
          title: 'استراتژی تونل',
          description: 'انتخاب بهترین مسیر بر اساس شرایط شبکه.',
          blockchain: 'رله بلاک‌چین',
          blockchainDesc: 'مسیردهی غیرمتمرکز.',
          applyButton: 'اعمال استراتژی',
          success: 'استراتژی با موفقیت اعمال شد.'
      },
      camouflage: {
          title: 'استتار ترافیک',
          description: 'شبیه‌سازی الگوی ترافیک عادی برای جلوگیری از شناسایی.',
          profile: 'پروفایل ترافیک',
          profileDesc: { ai: 'آموزش مدل هوش مصنوعی', data: 'همگام‌سازی دیتابیس', media: 'استریم ویدیو' },
          frequency: 'فرکانس چرخش',
          lessFrequent: 'پایدار',
          moreFrequent: 'پویا',
          status: 'وضعیت موتور'
      },
      appCamouflage: {
          title: 'استتار لایه اپلیکیشن',
          description: 'جا زدن ترافیک به عنوان بازی‌های آنلاین محبوب.',
          enable: 'فعالسازی شبیه‌ساز پروتکل بازی',
          profile: 'پروفایل بازی',
          codm: 'کال آو دیوتی موبایل',
          codmDesc: 'شبیه‌سازی UDP/443',
          pubg: 'پابجی موبایل',
          pubgDesc: 'شبیه‌سازی UDP/10000+',
          clash: 'کلش رویال',
          clashDesc: 'شبیه‌سازی TCP/9339',
          mmorpg: 'بازی‌های نقش‌آفرینی',
          mmorpgDesc: 'ترکیبی TCP/UDP',
          liveStatus: 'وضعیت زنده'
      },
      doh: {
          title: 'DNS امن (DoH)',
          description: 'فعالسازی DNS بر بستر HTTPS برای جلوگیری از شنود.',
          enable: 'فعالسازی سرور DoH',
          activeUrl: 'آدرس ریزالور فعال',
          subdomain: 'زیردامنه DNS',
          createButton: 'راه‌اندازی ریزالور',
          creatingButton: 'در حال ساخت...',
          deactivate: 'غیرفعال‌سازی',
          copy: 'کپی آدرس',
          copied: 'کپی شد!',
          status: { creating: 'در حال ساخت', failed: 'خطا', inactive: 'غیرفعال' }
      },
      iap: {
          title: 'پروکسی هویت‌محور (IAP)',
          description: 'استفاده از تونل گوگل (IAP) بدون نیاز به آی‌پی عمومی.',
          form: { projectId: 'شناسه پروژه', zone: 'منطقه (Zone)', instance: 'نام اینستنس' },
          info: { secure: 'Zero Trust', noPublicIp: 'بدون IP عمومی', tcpFwd: 'فوروارد TCP' },
          command: { title: 'دستور سمت کلاینت', description: 'این دستور را در سیستم کاربر اجرا کنید:', copy: 'کپی', copied: 'کپی شد' }
      },
      nat: {
          title: 'عبور از NAT',
          description: 'تکنیک‌های عبور از فایروال‌ها و NAT های سخت‌گیرانه.',
          status: 'وضعیت عبور',
          detectionBtn: 'تشخیص نوع NAT',
          modes: { 
              stun: 'STUN (P2P)', stunDesc: 'اتصال مستقیم با UDP Hole Punching.',
              turn: 'TURN (Relay)', stunDesc: 'استفاده از سرور واسط (Relay).',
              reverse: 'تونل معکوس', reverseDesc: 'اتصال خروجی به سرور واسط.'
          },
          stunServer: 'سرور STUN',
          turnServer: 'سرور TURN',
          turnUser: 'نام کاربری TURN',
          turnPass: 'رمز عبور TURN',
          keepAlive: 'فاصله Keep-Alive (ثانیه)',
          warning: 'حالت TURN نیاز به سرور واسط خارجی دارد.',
          holePunching: 'فعالسازی UDP Hole Punching',
          save: 'ذخیره تنظیمات'
      },
      sshSettings: {
          title: 'تونل‌های SSH',
          description: 'مدیریت پورت فورواردینگ محلی (-L) و ریموت (-R).',
          localTitle: 'فوروارد محلی (-L)',
          localDesc: 'دسترسی به سرویس‌های ریموت در لوکال.',
          remoteTitle: 'فوروارد ریموت (-R)',
          remoteDesc: 'در دسترس قرار دادن سرویس لوکال در ریموت.',
          bindPort: 'پورت Bind',
          target: 'مقصد (host:port)',
          addRule: 'افزودن قانون',
          useCase: 'موارد استفاده'
      }
    },
    login: {
      title: 'سامانه مدیریت عبور از تحریم',
      adminUser: 'نام کاربری',
      placeholderUser: 'نام کاربری را وارد کنید',
      passphrase: 'رمز عبور',
      placeholderPass: 'رمز عبور را وارد کنید',
      error: 'اطلاعات اشتباه است.',
      authenticate: 'ورود به پنل',
      statusLabel: 'وضعیت سامانه',
      tfaTitle: 'احراز هویت دو مرحله‌ای',
      tfaDescription: 'کد ۶ رقمی را از برنامه احراز هویت خود وارد کنید.',
      tfaPlaceholder: '۱۲۳۴۵۶',
      verify: 'تایید',
      forgotPassword: { title: 'بازیابی رمز عبور', description: 'ایمیل ادمین را وارد کنید تا لینک بازیابی ارسال شود.', forgotLink: 'فراموشی رمز؟', sendButton: 'ارسال لینک', backToLogin: 'بازگشت به ورود', successTitle: 'لینک ارسال شد', successMessage: 'لینک بازیابی رمز عبور به ایمیل شما ارسال شد.' }
    },
    notFound: { title: '۴۰۴', desc: 'صفحه یافت نشد.', home: 'خانه' },
    terms: {
        title: 'قوانین و مقررات',
        intro: 'استفاده از این سرویس به منزله پذیرش قوانین زیر است:',
        law1: '۱. این سرویس صرفاً جهت دور زدن تحریم‌های خارجی علیه متخصصین ایرانی ارائه می‌شود.',
        law2: '۲. دسترسی به محتوای غیراخلاقی، سایت‌های شرط‌بندی و شبکه‌های معاند مسدود است.',
        law3: '۳. هرگونه استفاده جهت حملات سایبری یا کلاهبرداری ممنوع است.',
        law4: '۴. مسئولیت استفاده از سرویس بر عهده کاربر است.',
        accept: 'می‌پذیرم'
    },
    dashboard: {
      userBase: 'کاربران', totalUsers: 'کل', liveConnections: 'اتصالات فعال', tunnelEstablished: 'تونل‌ها', totalData: 'ترافیک کل', encryptedPayload: 'ترافیک رمزنگاری شده', simulatedTraffic: 'نرخ انتقال', networkHealth: 'سلامت شبکه', connectionQuality: 'کیفیت', packetLoss: 'پکت لاس', jitter: 'جیتر', stabilityChart: 'پایداری', systemLogs: 'لاگ سیستم', geoDist: { title: 'توزیع جغرافیایی', users: 'کاربر' }, active: 'فعال', expired: 'منقضی', banned: 'مسدود', used: 'مصرفی', remaining: 'باقی‌مانده', optimalDns: 'DNS بهینه', avgRTT: 'پینگ', tlsActive: 'TLS فعال', tlsInactive: 'TLS غیرفعال', camouflage: { title: 'وضعیت استتار', jobStatus: 'وضعیت', running: 'در حال اجرا', idle: 'آماده‌باش', lastRun: 'آخرین اجرا', never: 'هرگز' }, quality: { Excellent: 'عالی', Good: 'خوب', Fair: 'متوسط', Poor: 'ضعیف' },
      ai: {
          analyze: 'تحلیل با هوش مصنوعی',
          analyzing: 'در حال تحلیل...',
          analysisTitle: 'تحلیل لاگ‌ها با AI',
          analysisError: 'دریافت تحلیل از هوش مصنوعی ناموفق بود.'
      },
      protocols: {
          title: 'آمار مصرف پروتکل‌ها'
      }
    },
    users: { 
        title: 'مدیریت کاربران', addUser: 'افزودن کاربر', usage: 'مصرف', expiry: 'انقضا', manageLinks: 'لینک‌ها', addModal: { title: 'کاربر جدید', quota: 'حجم (گیگ)', expiry: 'انقضا (روز)' },
        bulk: {
            actions: 'عملیات گروهی',
            delete: 'حذف انتخاب شده‌ها',
            extend: 'تمدید روز',
            addQuota: 'افزایش حجم',
            selected: 'مورد انتخاب شده'
        }
    },
    tunnel: {
      title: 'بهینه‌سازی تونل',
      description: 'بهترین مسیر ارتباطی بین سرور ایران و خارج را به صورت خودکار یا دستی انتخاب کنید.',
      autoPilot: 'خلبان خودکار',
      manual: 'دستی',
      nextTest: 'تست بعدی تا',
      disabled: 'تست خودکار غیرفعال است',
      analyzing: 'در حال تحلیل...',
      testNow: 'تست مسیرها',
      failed: 'ناموفق',
      pinging: 'در حال پینگ...',
      awaiting: 'در انتظار تست',
      activate: 'فعالسازی'
    },
    edgeStatus: { title: 'وضعیت سرور ایران', connectionTitle: 'وضعیت تونل', statusLabel: 'وضعیت', statusConnected: 'متصل', activeTunnel: 'پروتکل فعال' },
    camouflageSite: { title: 'پژوهشکده هوش مصنوعی', navHome: 'خانه', navApi: 'API', navContact: 'تماس', login: 'پرتال', signup: 'درخواست', status: 'وضعیت', statusIdle: 'عملیاتی', statusRunningAI: 'آموزش مدل', statusRunningData: 'همگام‌سازی', statusRunningMedia: 'دریافت مدیا', getStarted: 'شروع پژوهش', footer: '© ۱۴۰۳ تمامی حقوق محفوظ است.' },
    signup: { title: 'ثبت‌نام', description: 'اطلاعات خود را وارد کنید.', successTitle: 'دریافت شد', successMessage: 'درخواست شما بررسی می‌شود.', backButton: 'بازگشت', form: { name: 'نام و نام خانوادگی', email: 'ایمیل', reason: 'مورد مصرف', submit: 'ارسال درخواست' } },
    header: { systemSecure: 'ایمن', edgeNode: { connected: 'متصل', connecting: 'در حال اتصال', failed: 'قطع', notConfigured: 'تنظیم نشده' } },
    view: { dashboard: 'داشبورد', users: 'کاربران', settings: 'تنظیمات' },
    tooltips: {
        dashboard: {
            userCard: 'خلاصه‌ای از وضعیت کاربران شما بر اساس وضعیت فعلی آنها.',
            connectionsCard: 'تعداد کاربرانی که در حال حاضر به تونل متصل هستند و ترافیک رد و بدل می‌کنند.',
            dataCard: 'حجم کل داده‌های منتقل شده از آخرین ری‌استارت سرور و نرخ انتقال لحظه‌ای.',
            trafficChart: 'این نمودار ترافیک واقعی کاربران (آبی) و ترافیک استتار (سبز) را برای نمایش فعالیت شبکه شبیه‌سازی می‌کند.'
        },
        settings: {
            domainName: 'دامنه اصلی شما. برای تولید گواهی SSL و اتصال کلاینت‌ها استفاده می‌شود. مطمئن شوید رکورد A آن به آی‌پی این سرور اشاره می‌کند.',
            subscriptionDomain: 'یک دامنه جداگانه و اختیاری برای لینک‌های اشتراک کاربران. برای جداسازی صفحات کاربران از دامنه اصلی مفید است.',
            healthCheck: 'لیستی از زیردامنه‌های تولید شده را در برابر لیست‌های سیاه DNS آزمایش می‌کند تا آی‌پی‌های تمیز را پیدا کند. برای کلاینت‌ها در شبکه‌های بسیار محدود مفید است.',
            getCert: 'با استفاده از Let\'s Encrypt به طور خودکار یک گواهی SSL رایگان و معتبر برای دامنه شما درخواست و نصب می‌کند.',
            endpointStrategy: 'تکنولوژی زیربنایی مورد استفاده برای تونل را مشخص می‌کند. CDN برای استتار و VPS برای کمترین تأخیر بهترین گزینه است.',
            tunnelOptimization: 'نحوه تست و انتخاب بهترین مسیر ارتباطی بین سرورهای ایران و خارج را مدیریت کنید.',
            autoPilot: 'سیستم به طور خودکار تمام تونل‌ها را به صورت دوره‌ای تست کرده و به مسیری با بهترین عملکرد (کمترین تأخیر و جیتر) سوئیچ می‌کند.',
            manualMode: 'شما کنترل را در دست دارید. تونل‌ها را به صورت دستی تست کرده و مسیر فعال را انتخاب کنید.',
            camouflageProfile: 'الگوی ترافیک جعلی تولید شده توسط موتور استتار را تغییر می‌دهد تا بهتر با ترافیک عادی شبکه ترکیب شود.',
            camouflageFrequency: 'موتور استتار هر چند وقت یکبار الگوهای ترافیک خود را تغییر می‌دهد. تغییرات مکرر شناسایی را دشوارتر می‌کند اما ممکن است بار سرور را کمی افزایش دهد.',
            appCamoEnable: 'در صورت فعال بودن، سیستم تلاش می‌کند تا ترافیک شما را به عنوان یک بازی آنلاین محبوب مخفی کند تا فیلترینگ مبتنی بر پروتکل را دور بزند.',
            appCamoProfile: 'پروتکل بازی مورد نظر برای شبیه‌سازی را انتخاب کنید. هر پروفایل رفتار بسته‌های UDP/TCP آن بازی را تقلید می‌کند.',
            dohEnable: 'یک DNS-over-HTTPS resolver روی سرور شما فعال می‌کند. کلاینت‌ها می‌توانند از این برای رمزگذاری درخواست‌های DNS خود استفاده کنند که از مسمومیت DNS و مسدودسازی جلوگیری می‌کند.',
            dohSubdomain: 'زیردامنه‌ای که resolver DoH در آن در دسترس خواهد بود (مثلاً dns.yourdomain.com).',
            iap: 'پراکسی هویت‌محور گوگل به شما امکان می‌دهد تونل‌های امن به ماشین‌های مجازی خود بدون نیاز به IP عمومی ایجاد کنید و امنیت را افزایش می‌دهد.',
        }
    },
    roadmap: {
        title: 'نقشه راه توسعه',
        description: 'تیم ما دائما در حال کار بر روی ویژگی‌های جدید برای افزایش امنیت، کارایی و سهولت استفاده است. در اینجا برخی از بهبودهای هیجان‌انگیز آینده ما را مشاهده می‌کنید.',
        status: {
            researching: 'در حال تحقیق',
            planned: 'برنامه‌ریزی شده',
            in_progress: 'در حال توسعه',
            beta: 'نسخه بتا'
        },
        items: [
            {
                title: 'پیشنهادات هوشمند',
                description: 'هوش مصنوعی Gemini الگوهای ترافیک کاربران را تحلیل کرده تا بهترین مکان سرور و پروتکل بهینه را برای کاربران جدید پیشنهاد دهد.',
                status: 'in_progress'
            },
            {
                title: 'تشخیص خودکار ناهنجاری',
                description: 'سیستم به طور خودکار فعالیت‌های غیرعادی کاربر، مانند مصرف ناگهانی پهنای باند بالا را شناسایی و برای جلوگیری از سوءاستفاده گزارش می‌دهد.',
                status: 'planned'
            },
            {
                title: 'اپلیکیشن‌های اختصاصی کلاینت',
                description: 'یک اپلیکیشن اختصاصی چند پلتفرمی (ویندوز، مک، اندروید، iOS) برای اتصال با یک کلیک و همگام‌سازی آسان پروفایل‌ها.',
                status: 'planned'
            },
            {
                title: 'احراز هویت غیرمتمرکز',
                description: 'یکپارچه‌سازی با سیستم‌های هویتی مبتنی بر بلاک‌چین برای افزایش حریم خصوصی و مقاومت در برابر سانسور.',
                status: 'researching'
            },
            {
                title: 'موتور استتار پویا',
                description: 'موتور استتار با یادگیری از ترافیک شبکه به صورت زنده، الگوهای ترافیکی متقاعدکننده‌تری ایجاد کرده و خود را با تغییرات شبکه تطبیق می‌دهد.',
                status: 'researching'
            }
        ]
    }
  }
};
